baseURL = "https://alobbs.com/"
languageCode = "en-us"
title = "alobbs.com"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Alvaro Lopez Ortega"
  description = "ğŸ“Œ Director of Eng at Pinterest & Tech Board Member at Inditex â€” ğŸš€ Former eBay, Docker, Meta, Akamai, Red Hat, Canonical, Sun â€” ğŸ§  Infrastructure at Scale, Open Source"
  github = "alobbs"
  linkedin = "alobbs"
  bluesky = "alobbs.com"
  # email = "alobbs@gmail.com"
  url = "https://alobbs.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "United States"
  userStatusEmoji = "ğŸ¡"
  enableGitalk = false
  enableSearch = true

  [[params.links]]
    title = "Signal"
    href = "https://signal.me/#eu/PN6so6Yj1zF8-ZRXu-g7elbpyQKnjykenToMnwnW0qDsuT1sm35Gt4e4tyupw2-N"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
